// Crie uma lista vazia, com o nome listaGenerica.
// Crie uma lista de linguagens de programação chamada linguagensDeProgramacao com os seguintes elementos: 'JavaScript','C','C++', 'Kotlin' e 'Python'.
// Adicione à lista linguagensDeProgramacao os seguintes elementos: 'Java', 'Ruby' e 'GoLang'.
// Crie uma lista com 3 nomes e exiba no console apenas o primeiro elemento.
// Crie uma lista com 3 nomes e exiba no console apenas o segundo elemento.
// Crie uma lista com 3 nomes e exiba no console apenas o último elemento.

const listaGenerica = []

const linguagensDeProgramacao = ['javascript', 'C', 'C++', 'Kotlin', 'Python']
linguagensDeProgramacao.push('Java')
linguagensDeProgramacao.push('Ruby')
linguagensDeProgramacao.push('GoLang')

console.log(linguagensDeProgramacao[0]);
console.log(linguagensDeProgramacao[1]);
console.log(linguagensDeProgramacao[2]);

